### ISSUE TITLE
goBack()方法报错

### ISSUE THREAD

**Issue by syanbo** [shimohq/react-native-x5#5]
React-Native 0.44
调用 X5WebView goBack() 方法报错 
typeerror: expected dynamic type 'double' but had type 'null'
UIManager.dispatchViewManagerCommand at argument index 0

**Comment by WHZWHZ1229** [comment]
在class上方加var RCT_WEBVIEW_REF = 'webview';然后在render()里面的RNX5WebView中加ref={ RCT_WEBVIEW_REF }
